repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        types: [python]
        args: [--exclude, tests]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^traincheck/
        types: [python]
        args: [--install-types, --non-interactive, --ignore-missing-imports] 
        # args: [--strict]

  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        types: [python]
        args: [--exclude, tests]
        # args: [--check]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black, --skip, tests]