global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'neutracer'
    static_configs:
      # - targets: ['host.docker.internal:9091']  # 魔法域名
      - targets: ['172.17.0.1:9091']  # 魔法域名